<img src="https://i.pinimg.com/originals/68/14/fc/6814fcbac067bfe0b6d4bdeeb17c7553.jpg" style="display:block;margin-left: auto;margin-right: auto;width:15%;height:auto;text-align:center;">

<h1 style="margin-bottom: 0.2em;text-align:center"> MPhys Project - Machine Learned Potentials For MD Simulations
<h2 style="margin-top: 0.2em;text-align:center"> University of Exeter EMPS
<h3 style="margin-top: 0.2em;text-align:center"> Natan Szczepaniak<h4 style="margin-top: 0.2em;text-align:center"> Supervisor: Prof. Saverio Russo

<h1 style="text-align:center;">CONTENTS</h1>
<ul style="list-style-type:none;font-size:1.75rem;font-style:itallic">
    <li style="margin:10px 0;"><b>Week 1</b> - Planning Year</li>
    <li style="margin:10px 0;"><b>Week 2</b> - Setting up Virtual Server Environment</li>
    <li style="margin:10px 0;"><b>Week 3</b> - Running SIMPLE-NN Code for SiO2 \& Edge detection for others</li>
    <li style="margin:10px 0;"><b>Week 4</b> - LAMMPS Simulation script using the NN potential and ISCA</li>
    <li style="margin:10px 0;"><b>Week 5</b> - OVITO analysis of SiO2</li>
    <li style="margin:10px 0;"><b>Week 6</b> - Tersoff Potential explanation and email to S. Hepplestone</li>
    <li style="margin:10px 0;"><b>Week 7</b> - Presentation for S. Hepplestone \& sp2-sp3 hybridisation explanation</li>
    <li style="margin:10px 0;"><b>Week 8</b> - Joe Pitfield Data \& DFT summary</li>
    <li style="margin:10px 0;"><b>Week 9</b> - ASE python script for validating VASP data for SIMPLE-NN</li>
    <li style="margin:10px 0;"><b>Week 10</b> - Catchup \& Behler-Parinello Method Revision</li>
    <li style="margin:10px 0;"><b>Week 11</b> - Admin for viva \& Graphene Tersoff Potential </li>
    
<ul>

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 1 (21/09/20-27/09/20)<ins></h2><br>

This week was spend planning the term and the focus of the project. Main thing that was discussed was the use of the ISCA Supercomputer or any other research environment we can use for the project. We discussed this with Prof. Russo and he said he would gain us access. After trails of setting up a proper environment last year and knowing how long it will take to gain access, I suggested setting up a virtual machine on my computer that I can make accessible via SSH. I would transfer all the relevant software onto this machine along with the output data from last year.

We acknowledged it would take all of us to catch up with the work done last year. As a reminder of the progress we did last year I suggested others to read through my notes. We also agreed that we would read the SIMPLE-NN and aenet paper again to get a refresher of what we did. 

The others had some concerns about how they don't feel comfortable with the project as much and would require more guidance on this. They also asked whether they could go back to the labs to carry on with the previous project from before COVID-19 however due to lab closure this was impossible. Nevertheless, they decided to pursue this project splitting the tasks up into manageable tasks. The research was broken into

* Natan (Me) - Simple-NN / LAMMPS
* Max - Aenet
* Nathan - LAMMPS

For now everyone decided to use the week to catch up on where we left of whilst I set up the environment for everyone to work in. 

Another thing that was discussed was finding out more about the type of structure we should be studying. I suggested emailing Dr Steve Hepplestone to get more insight. I believe this should be postponed until we have some more solid work to show and go off of as otherwise it would be unfruitful.

Later on in the week I gathered all of the virtual hard drives from last year and picked out key things that were needed. Main requirements for a research environment were:

- SIMPLE-NN
- aenet
- LAMMPS
- Dependencies
- OpenSSH
- SFTP enabled
- Ranger
- Vim

I believe that UBUNTU Server 18.04 would be the best choice due to the software mentioned would be easiest to get running on it and it would be easy to use for others to use. 
    
## Bibliography:
- Sivaraman, G., Krishnamoorthy, A.N., Baur, M. et al. Machine-learned interatomic potentials by active learning: amorphous and liquid hafnium dioxide. npj Comput Mater 6, 104 (2020).(https://www.nature.com/articles/s41524-020-00367-7)
<br>
- Tersoff J. New empirical approach for the structure and energy of covalent systems. Phys Rev B Condens Matter. 1988 Apr 15;37(12):6991-7000. doi: 10.1103/physrevb.37.6991. PMID: 9943969.(https://journals.aps.org/prb/abstract/10.1103/PhysRevB.37.6991)
<br>
- SIMPLE-NN: An efficient package for training and executing neural-network interatomic potentials (https://www.sciencedirect.com/science/article/pii/S0010465519301298)
- LAMMPS 30 Nov 2020 Documentation (https://lammps.sandia.gov/doc/Manual.html)
- sp2/sp3 Carbon Ratio in Graphite Oxide with Different Preparation Times J. Phys. Chem. C 2011, 115, 6, 2705–2708 (https://pubs.acs.org/doi/10.1021/jp107906u)
- ANI-1: an extensible neural network potential with DFT accuracy at force field computational cost https://pubs.rsc.org/en/content/articlelanding/2017/sc/c6sc05720a#!divAbstract
- Generalized Neural-Network Representation of High-Dimensional Potential-Energy Surfaces https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.98.146401
- An Introduction to Density Functional Theory - N. M. Harrison https://www.ch.ic.ac.uk/harrison/Teaching/DFT_NATO.pdf
- Toward Reliable and Transferable Machine Learning Potentials:Uniform Training by Overcoming Sampling Bias https://pubs.acs.org/doi/pdf/10.1021/acs.jpcc.8b08063
    
## Videos:
    
- Molecular Dynamics Simulation of Carbon Nanotube in Water Using LAMMPS https://www.youtube.com/watch?v=9GbjlSqY4Vk
- LAMMPS Online course May 2020 : Week 1 https://www.youtube.com/watch?v=p3izaBP6gs0
- LAMMPS Online course May 2020 : Week 2 https://www.youtube.com/watch?v=h2e_LYbls7g
- Fundamentals and applications of density functional theory - Astrid Marthinsen (Norwegian University) https://www.youtube.com/watch?v=SXvhDLCycxc
- MIT 3.021J Introduction to Modeling and Simulation, Spring 2012 https://www.youtube.com/watch?v=HkoxlFUerR0

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 2 (28/09/20 - 04/10/20)<ins></h2><br>

Set up environment for development with others UBUNTU Server 18.04

This week I gathered possible solutions for the hardware I should use for this project. I considered building a home server with a lot of cores and spare parts I have however this came out rather pricey. After a lot of research for the best solution for the project I came to the conclusion that I should host a virtual machine on my computer, open up the port for SSH connections and connect remotely. This would allow for the use of my main computers resources remotely and collaboratively.

I began by setting up a virtual machine using virtualbox

<img src="https://i.imgur.com/Wnj1NgW.png" style="width:700px;height:auto;">

Then I downloaded the iso and installed Ubuntu Server 18.04 which is the CLI version of Ubuntu with less unneeded features. Next I set up an internet connection using a Bridged Adapter connection.
I created 3 accounts for everyone and installed the correct software in everyones home directory so that everyone can have their own installation to learn with.

<img src="https://i.imgur.com/bCAI0TT.png" style="width:700px;height:auto;">

Next, to make this available to others I ran the following command to enable the ssh port to the server.

<pre><code>
sudo ufw allow ssh
</code></pre>

Next, I went on my router admin settings and port forwarded the open port of my local machine to the local port of the router. This allows my colleagues to use connect to my virtual machine directly anywhere in the world with my home IP. 

<img src="https://i.imgur.com/WCrJbqO.png" style="width:700px;height:auto;">

This is not a very secure way of establishing a connection however security wasn't a priority in this project and none of the data was sensitive. Doing things this way also ensured that it was easier for my colleagues to connect via Putty of some other SSH client. 

I invited the others to join my server and helped them set up their accounts. As they didn't have much previous experience using a Linux Environment I had to teach them them how to manoeuvre round the workspace.

At the end of the week, we had a meeting to discuss this progress. With the Prof. Russo, he was impressed with the progress I made. Max mentioned he will take it upon himself to tackle understanding aenet for others and mentioned the documentation was good. 

I set up all of the dependencies for SIMPLE-NN to run and prepared it for next week. The server is now open to the world through my router meaning I can access it from anywhere. 
    
This is a much bigger improvement from last year's setup as everything is localised in once place. LAMMPS \& SIMPLE-NN being the main important ones. I also back up this system to a harddrive mostly every week to prevent data loss as thats just scary.
    
This process took some time: 
- Setting up the virtual server
- Installing correct software/dependancies
- Set up everyones environment with the correct permissions and version of bash
- Set up OpenSSH
- Bridged Internet connection from main computer's network card
- Port-forwarding
    
I am going to leave this for the week and now that all of this is set up, I am ready to resume back into the physics.

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 3 (05/10/20 - 11/10/20)<ins></h2><br>

## 3.1 Machine Learned Potentials

I started off the week with running SIMPLE-NN again for SiO2 from scratch. The ab initio data included is of melt-quench simulations. The data training data consists of 108 atoms. This time, using 4 cores, it took 4 hours to finish and gave an output file "potential_saved_iteration5001".

These are the first 14 lines of the output:

<pre><code>
ELEM_LIST Si O

POT Si 6.0
SYM 70
2 6.0 0.003214 0.0 0.0 Si
2 6.0 0.035711 0.0 0.0 Si
2 6.0 0.071421 0.0 0.0 Si
2 6.0 0.124987 0.0 0.0 Si
2 6.0 0.214264 0.0 0.0 Si
2 6.0 0.357106 0.0 0.0 Si
2 6.0 0.714213 0.0 0.0 Si
2 6.0 1.428426 0.0 0.0 Si
2 6.0 0.003214 0.0 0.0 O
2 6.0 0.035711 0.0 0.0 O
</code></pre>

This is the same as the symmetry function that was fed into the equation. 

<pre><code>
w27 -0.7471374918482107 -1.0464086491701752 -0.1759303792772614 0.15673034896121268 -0.034262988987879654 -0.24487035797040912 -0.04149586988080609 -0.8422304105831314 -0.1559079189082922 0.24446654802556345 -0.09222074916104225 -0.9252648078673837 -0.2703078543426878 0.48583216677692925 -0.05862375045424141 -0.35198490889440404 -0.6142745035536875 -0.5676753118899953 0.04818201503341462 0.07449716643424008 -0.053663487654484116 -0.23361056814728617 -0.12163653216539366 -0.16635107175395192 0.9669276979924982 -0.6578003802003811 -0.0792282384003453 -0.47680700513198704 -0.5299770648104948 0.14228790525009333
b27 0.3017768813615731
w28 0.1955569519163051 0.4363155533641985 -0.6617027949095984 -0.03380587693805343 -0.2986066360664528 -0.3240100181622036 0.31955715641718063 -0.18316947346274254 -0.4031320453011955 -0.06757987924411828 -0.1051888253265337 0.0028504114627909342 -0.6997852653709132 -0.5151195672337664 -0.23089005153268322 -0.12679733316587496 -0.5255292992390612 -0.16498362170301734 0.2042913379278798 0.09060296504032243 0.20743391176214324 0.10334249576013964 -0.06422232335727 0.04909290795089136 0.0698318631512599 0.032450025026642085 0.4225263771763582 -0.3574525690490653 -0.21644091559468026 -0.3116451007833061
b28 -0.3626596139276706
w29 -0.39230008514398773 0.326618239197014 -0.009760706340364769 0.2923558184518605 -0.6193942292823895 0.11853264887318314 0.39160903335984676 -0.25953408822980634 -0.3361180419009118 0.34541818681504155 0.298259798683223 0.2981818728139801 0.6122001378755157 0.362556748298222 0.3047557837906453 0.02889869383749455 0.0937849646846054 0.020821969228581705 -0.41601909439444684 -0.06398686664663197 -0.20144378302599553 -0.5925078337895555 -0.1961557417815917 -0.48584734859271544 0.2106617849262458 -0.47844970327614 0.6069687198374991 0.5504052558430916 0.40014794303182166 0.15232389937425775
b29 -0.08825863721754094
</code></pre>

The latter part of the output contains the weights and biases of the neural network in its final position. This is then parsed by the C++ pair_style written for LAMMPS which converts it into atomic energy. 

This has the form

<pre><code>
(weight node number) (30 weights)
(bias node number) (1 bias)
</code></pre>

These are the raw pair_coeff arguments used inside LAMMPS. This will later be used to fill out the parameters for the custom "pair_nn" pair_style (potential style) when running the classical simulation. So far I have only ran one simulation for silicon using a Lennard Jones Potential after following a guide.

<img src="https://i.imgur.com/fUWjA9A.png" style="width:400px;height:auto;">

In order to use this structure I would have to write my own input script that has two elements Si & O which I dont yet know how to do. I would initially simulate this using a classical potential built into lammps. Then I will move on to using the potential derived from the SIMPLE-NN software. 

My group members asked me a lot of questions about how to run the software because they were having a lot of difficulties with running it. After a group meeting with our supervisor. Others decided to change focus of their project as they found it too difficult. 

Prof. Russo suggested an alternative experiment for others to do at home which involved creating a spectrometer using materials available at home. We were not very open to this idea as it involved too much going wrong. 

## 3.2 Edge detection 

Eventually, our supervisor suggested the idea of analysing data collected by others in the lab. He suggested using data from Raman spectroscopy experiments from Phd students. One of the first things that was discussed was calculating the relative thickness of flakes of HfO2. This could be done by sampling one of the flakes and comparing the value to another flake. The more quantitative way of doing this would be to sum over all of the values, take an average (together with an uncertainty) and compare these values to the others. 

In order to achieve this, you would need to find the edges of the flakes to let the program automatically calculate these differences. 

From all of the algorithms I found, Canny's edge detection was the most useful. I looked into writing my own software to do this however it would be a waste of time when python has many libraries have it prewritten and as a prototype it should be satisfactory.

As the others had a few problems with getting this going, I wrote them a script using the opencv2 library to find the edge of the flakes. 

<pre><code>
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm
from scipy import ndimage as ndi

from skimage import feature

# Sources image, extracts green channel finds edges from parameters
src = cv2.imread("input.png", cv2.IMREAD_UNCHANGED)

im = src[:, :, 1]  # Green Channel
edges = np.array(255*feature.canny(im, sigma=9,
                                   low_threshold=0.01,
                                   high_threshold=0.50))

# Prints number of edge pixels
unique, counts = np.unique(edges, return_counts=True)
print(dict(zip(unique, counts)))

# Adds arrays together
result = np.add(im*-5, edges)

cmap = matplotlib.cm.bwr

plt.imshow(result, cmap=cmap)
plt.show()
</code></pre>

This script extracts the green channel from a given image (as this is the one of study). Loads it into a numpy array and runs the opencv canny method. 

Flake image initially
<img src="https://i.imgur.com/jyyunDq.png" style="width:200px;height:auto;">

Flake image selection matrix
<img src="https://i.imgur.com/O0fnMXp.png" style="width:200px;height:auto;">

Selection matrix imposed onto image
https://i.imgur.com/fCPUkZe.png
<img src="https://i.imgur.com/fCPUkZe.png" style="width:200px;height:auto;">

The results it obtains is a matrix of 1 or 0 values of where the edge is found. This should later be joined up by changing the parameters, finding an average pixel value by scanning the selected are taking samples of 3x3 matrices and finding the average. After each flake is done, this should find the relative thickness of each flake. 

This edge detection was just a bit of an experiment of whether I would like to work on this project. Despite finding this process enjoyable and the topic was much more approachable I feel like I didn't have as much to learn in this one compared to my initial project. I have also committed enough to my previous project and would like to proceed even though it is difficult. I am learning much more about the things I would like to learn about.

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 4 (12/10/20 - 18/10/20)<ins></h2><br>


## 4.1 LAMMPS Input Script

This week I spent learning more about writing LAMMPS input scripts. My main source of this is the ARCHER LAMMPS tutorial series which goes through the use of LAMMPS and applying it for a HPC environment. This is the same tutorial that I used the simulation of Bulk Silicon.

ARCHER LAMMPS 2020 Tutorials:

* Part 1: https://www.youtube.com/watch?v=p3izaBP6gs0
* Part 2: https://www.youtube.com/watch?v=h2e_LYbls7g 

I used this supplemented with online forums to find out how to simulate more than one element. For this run I decided to stick with the simple cubic stucture (For real SiO2 it should be hexagonal {hpc}) for simplicity. 

This is the script I came up with.

<pre><code style="color:blue;">
# Title: Silicon Dioxide LAMMPS input script
# By: Natan Szczepaniak

# First input script which uses SIMPLE-NN generated potential
# to simulate Silicon Dioxide.


# 1) Setting up the simulation box

units		metal		# units
atom_style	atomic		# atoms are spheres
dimension	3		# 3 dimensions
boundary	p p p		# p - periodic boundaries 

lattice sc 2.65 		# sc - simple cubic
				# 0.6 - density 

region box block 0 10 0 10 0 10 # create a box of shape "block" (10x10)
create_box 2 box		# create box of atoms of 2 types

# Create Si atoms
create_atoms 1 region box

# Create O atoms
lattice sc 2.65 origin 0.3 0.3 0.3
create_atoms 2 region box

</code></pre>

First part of the script sets up the simulation box together with creating the atoms. 

<pre><code style="color:blue;">

# 2) Define interparticle ineractions (SIMPLE NN potential)

pair_style nn			# SIMPLE-NN potential file (.cpp)
pair_coeff * * /home/lammps_input/potential Si O # "* *" means every type interacts with every type with following coeffs

mass 1 28.0855			# Silicon mass 28.0855 grams/mol
mass 2 15.998			# Oxygen mass 15.998 grams/mol
</code></pre>

This is where the SIMPLE-NN potential is inputted and the mass of atoms is set. 

<pre><code style="color:blue;">

# 3) List of Neighbours (Neighbor lists are recalculated 
# each timestep.)

neighbor 2.0 bin		# Neighbour list 2.0 Angstrom

# neigh_modify delay 100 every 10
# neigh_modify delay 0 every 1 check yes page 500000 one 50000

</code></pre>

Neigbour lists make the simulation more efficient as it only considers atoms nearby.

<pre><code style="color:blue;">

# 4) Define Simulation parameters (Temperature, Momentum, etc.)

fix 3 all nvt temp 300.0 300.0 0.01
</code></pre>


This sets up the process in the simulation box. In this example, the box is simply kept at 300K


<pre><code style="color:blue;">
# 5) Final setup
#   - Define starting particle velocity
#   - Define timestep
#   - Define output system properties (temp, energy, etc.)
#   - Define simulation length
#
#velocity        all create 300 199085 mom no rot no
#
#timestep	0.005
#
#thermo_style 	custom step temp etotal pe ke press vol density # All of the outputs to log
#thermo 		10		# print at multiples of N
#
#run_style verlet
#
#run 200
#
# Output file

dump		2 all custom 10 positions.lammpstrj id type x y z vx vy vz
dump_modify	2 sort id

run 2000
</code></pre>

This step outputs all of the data into a file called positions.lammpstrj in the format given above and sorts the output by id. Alternatively you can also output this as a RDF plot or a Phonon spectrum. These outputs will be used to compare my simulations to the DFT calculations from the ab initio data for comparison. I will also visualise the structure to asses what is going on easier. 

In order to visualise and use my findings in OVITO, I need to specify the id, type, coordinates and velocities that will be output every timestep.
    
<code><pre>  
dump		2 all custom 10 positions.lammpstrj id type x y z vx vy vz
</pre></code>
    
Ensures the correct data is outputted however we can output whatever we would like Total energy, Potential Energy, etc. each timestep.
    
The form of this data "dump" as described in the LAMMPS documentation is:
    
<code><pre> 
dump		[ID] [Group-ID] [style]  [N] [filename] [args]
</pre></code>
   
As it states in the documentation:
    
> - ID = user-assigned name for the dump
>
> - group-ID = ID of the group of atoms to be dumped
>
> - style = atom or atom/gz or atom/zstd or *atom/mpiio or cfg or cfg/gz or cfg/zstd or cfg/mpiio or custom or custom/gz or custom/zstd or custom/mpiio or dcd or h5md or image or local or local/gz or local/zstd or molfile or movie or netcdf or netcdf/mpiio or vtk or xtc or xyz or xyz/gz or xyz/zstd or xyz/mpiio
>
> - N = dump every this many timesteps
>
> - filename = name of file to write dump info to
>
> - args = list of arguments for a particular style

We used a "custom" style as we want to specify our own terms for the output of the system.   
    
Additionally there is a difference between different outputs:
- thermo - output to console
- dump - output to file
- fix - set parameters for output to file
  
I kept the thermo ones in as it gives an output to the console whilst the simulation is running.
    
## 4.2 ISCA Supercomputers

This week I also connected to the University Supercomputers. This is the email I recieved 

>Dear ISCA user,
>
>Thanks for registering your interest in using the ISCA HPC Cluster.
>
>You should now be able to log in to the ISCA HPC Cluster using your normal University user name and password.
>
>Before you start using the HPC please be aware that it is a batch system so there is some reading involved. Pay special attention to the sections
>
>If you have not used Linux or HPC before we have posted a workshop which should help you get up to speed with the very basics here: http://login.
>
>Answers to the workshop can be found here: http://login.isca.ex.ac.uk:8080/Workshop/WorkshopAnswers.pdf
>
>To run jobs through the job scheduler which runs on CentOS 7, or to access Openstack to create your own VMs with the operating system of your cho
>By default, only project PI’s are included in project groups.                      
>If you are not a project PI, you should talk to your PI about getting access. PI’s can add additional members to the project on the login node.
>
>Further information about project groups can be found in the Exeter ARC Sharepoint
>
>If you have any problems or questions that are not covered by the user guides, please let us know at isca-support@exeter.ac.uk and one of our tea
>
>
>Rosie Rowlands
>
>Research IT Officer (HPC)
>
>Exeter IT

In order to connect to the HPC facility, I had to first access the University VPN to be able to access it via SSH. After some research I found the best way to set this up would be using PulseSecure which is the VPN client the University recommends the use. 

<img src="https://i.imgur.com/gKeSahC.png" style="">

To log into the VPN I used my standard University login and password at a URL given by the university.

Then, once connected to the VPN, It was as simple as SSH-ing into the server with an account. The Supercomputer runs on CentOS 7 (Free version of RedHat Linux) with Openstack virtualisation software for experimentation together with SLURM used for scheduling tasks. 

However I don't need it right now, it will come in useful when I have to run more intensive calculation in the future.

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 5 (19/10/20 - 25/10/20)<ins></h2><br>

I spent this week mostly dealing with bugs to do with the LAMMPS input script. The two main issues I had were:

* pair_coeffs not taking in enough arguments.
* list of nearest neigbours size was too big or too small (optimisation for efficiency)

I then successfully ran the simulation generating a simple cubic SiO structure of 10x10 lattice points (2000 atoms). This is not an accurate output however it demonstrates a machine learned potential being used to simulate a structure in LAMMPS.

I then visualised this using OVITO. I decided to use OVITO over VMD as it provides a much better interface and more features. From this simulation I gathered an animated visualisation of 2000 steps of calculation shown below. 

<img src="https://s8.gifyu.com/images/SiO.gif" style="width:500px;height:auto;">

This is quite a big step in the right direction for the project as the method of converting OUTCAR data into a potential is established. The next step in the project will be finding a material to focus on. I believe that using HfO2 just because it is the one that is convenient is not a good enough reason. Next week, I will contact Steve Hepplestone to see whether this would be of any interest to him and his project. 

I believe this is enough content to present in order to get more of a perspective of where I am in the project and direct it more towards the final product. During a meeting this week, Prof Russo mentioned that if I get this to work and are able to explain it it would be enough for the masters project as it is now, however I would like to take it further. I would like to choose a structure, run DFT calculations on it, run a classical simulation, derive an NN potential and run another classical simulation with the derived potential and compare the outcomes RDF/Phonon Dispersion.
    
For now, I will find the averaged RDF of this system. To take a usable RDF the temperature needs to be kept constant. I set the temperature to be constant at 300K, however with 2000 particles the RDF was not accurate therefore I decided to average it over a period of time (100 timesteps). This could be done within lammps itself however I would prefer to do it manually using Python.
    
Ovito gives the radial distribution function each timestep and gives a live plot as the simulation goes on. 

<img src="https://i.imgur.com/l4asmeJ.gif" style="width:400px;height:auto;">

This data can then be exported as a txt file for each timestep and then a python script can be used to find the averaged out rdf over time and plotted using matplotlib.
    
<img src="https://i.imgur.com/yXoR4gr.png" style="width:500px;height:auto;">
    
This is the RDF of SiO2 at 300K using the NN interatomic potential derived using the Behler Parinello method using SIMPLE-NN and LAMMPS. The plan is to find another structure to try all 3 methods to simulate the same system, calculate the RDF just like this one and compare the accuracy keeping DFT as the desired output (even though it is not ideal, it is close enough to reality to consider it as a benchmark.)
    
This week was quite demanding with fixing bugs and parsing the data from OVITO/LAMMPS that I will finish for this week. Like mentioned before, this is a big milestone however the structure at hand still needs to be found. This is not an analysis of a structure but a comparison of different methods and their efficiency. 
    
Next week I will email Steve Hepplestone asking about the direction of the project and perhaps find out what structure I should be looking at.

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 6 (26/10/20 - 01/11/20)<ins></h2><br>

## 6.1 Direction of the project
    
Direction of project unclear, Emailed Steve Hepplestone about it 

>Dear Dr Hepplestone,
>
>I am writing to you to ask for guidance on my MPhys project I am working on and potentially arrange a meeting if you would be able to find some time. My current supervisor is Saverio Russo 
>
>After my initial project plan studying memristive materials for RRAM devices was scrapped due to lack of access to labs, my group was asked to change our project to a more theoretical appro
>
>I am aware that potentials can be regressed from both experimental and first principle (DFT) data manually however after doing more research I found that using a High Dimensional neural net
>
>During the time I had on this project I got little to no guidance from my supervisor as it is not the area of his expertise. So far I have been doing everything on my own having had to teac
>
>Researched different regression methods (settled on HDNN with descriptors)
>Found 3 implementations of this in practice (One of which being the original source code directly obtained from from Dr. Jörg Behler - the person who invented this method)
>Installed and learned how to write LAMMPS (MD software) input files having simulated bulk silicon
>Set up my own UNIX based home server/lab to run these simulations (and made it accessible to my colleagues via SSH) whilst waiting for a response to get access to ISCA
>Got access to ISCA and successfully set up account.
>Used one of the implementations (SIMPLE-NN) to find the potential for SiO2
>Successfully used the derived potential in LAMMPS and visualised in OVITO & VMD. (The output was questionable to say the least)
>As my other colleagues recently switched their project focus to something else as they found this too difficult, I have been left alone with no help and naturally feel lost which is why I a
>
>What I would like to do now is to use this method to simulate a process on using HfO2 or graphene and obtain a radial distribution function or some other output I can use to compare the acc
>
>
>If possible I would appreciate if I could get your insight or if you know anyone else in the department that could help me with this as I am concerned that I will not have much of value to 
>
>Thanks,
>
>Natan Szczepaniak

## 6.2 Bond Order Empirical Potentials (Tersoff)
    

    
As I had not much else to do after a milestone, I decided to learn more about Classical Potentials and how they can be used for analysis. In particular I looked at the Tersoff Potential.
    
Tersoff Potential is a type of a Empirical bond order interatomic potential. The advantage of this type of empirical potential that sets it apart from standard classical empirical potentials such as Lennard Jones is that it can model different bonding states of an atom.
    
This is dervied from the relation of bond strength and the bonding environment parameters. These include bond lengths, angles and the number of bonds.
    
The general form of the potential looks like this:
    
<!--\begin{split}
    E & = \frac{1}{2} \sum_i \sum_{j \neq i} V_{ij}
\end{split}--->
    
\begin{split}
V_{ij} & = f_C(r_{ij}) \left[ f_R(r_{ij}) + b_{ij} f_A(r_{ij}) \right] \end{split}
    
This potential consists of the repulsive two body repulsive term $f_R(r_{ij})$ and an attractive three-body term $f_A(r_{ij})$. All of this is enclosed by a cut off function $f_C(r_{ij})$ that sets the potential for each atom pair at $r>R+D$ where R+D is the cutoff distance. This is chosen to only include the first-neighbor shell.
    
The $f_A(r_{ij})$ three body term is multiplied by $b_{ij}$ is the bond order which depends on the environment of three particles. More on this later.
  
Here are the respective forms of each one of the functions:
    
\begin{split}
f_R(r) & =  A \exp (-\lambda_1 r) \\
f_A(r) & =  -B \exp (-\lambda_2 r) \\
f_C(r) & = \left\{ \begin{array} {r@{\quad:\quad}l}
  1 & r < R - D \\
  \frac{1}{2} - \frac{1}{2} \sin \left( \frac{\pi}{2} \frac{r-R}{D} \right) &
    R-D < r < R + D \\
  0 & r > R + D
  \end{array} \right. \\
\end{split}
    
$R,D,\lambda_1,$ and $\lambda_2$ are all parameters that need to be fed into the potential manually and are usually obtained by experimental/DFT calculations. By now, for majority of environments these parameters are mostly well established and are widely available for popular chemical systems such as Si-O and C-C.
    
As mentioned before, $f_A(r_{ij})$ is multiplied by the bond order term which relies on the three body interactions which are key to the bond strength modelled by the interatomic potential. This term can increase or decrease the attractive force which is modelling the bond. The magnitude of this term (hence strength of bond) is determined by the environemnt of the system for example it would be lowered when the number of neighbours is high and increase when number of bonds is relatively low. 

\begin{split}
b_{ij} & =  \left( 1 + \beta^n {\zeta_{ij}}^n \right)^{-\frac{1}{2n}} 
\end{split}
    
This relationship comes from the $\zeta_{ij}$ term.
    
\begin{split}
\zeta_{ij} & =  \sum_{k \neq i,j} f_C(r_{ik}) g(\theta_{ijk})
                 \exp \left[ {\lambda_3}^m (r_{ij} - r_{ik})^m \right] 
\end{split}

We see this from the exponent $\exp \left[ {\lambda_3}^m (r_{ij} - r_{ik})^m\right] $. The bigger the difference between $r_{ij}$ and $r_{ik}$ the bigger the $\zeta_{ij}$ term, the smaller the $b_{ij}$ therefore the weaker the bond.
    
Another important aspect of this potential is the angle of the bond (coordination of the system). The $\zeta_{ij}$ term includes a function $g(\theta_{ijk})$ where $\theta_{ijk}$ is the angle between the atoms $i,j$ and $k$.
     
\begin{split}
g(\theta) & =  \gamma_{ijk} \left( 1 + \frac{c^2}{d^2} -
                \frac{c^2}{\left[ d^2 + (\cos \theta - \cos \theta_0)^2\right]} \right)
\end{split}
    
The coordination of the three body system includes a lot of bond-specific terms, however the most important part is that the minimum for this function (where the bond is the strongest) is where $h=cos(\theta)$ as then the denominator goes to $d^2$ meaning $g(\theta)=1$.
    
###  Example (Carbon with 120$^o$ bonds)
    
As mentioned, the parameters for these systems is quite well established for systems such as Si or C. Here is a table of parameters for Tersoff Potentials I found [here](http://phycomp.technion.ac.il/~david/thesis/node24.html).
    
<img src="https://imgur.com/XqjHav6l.png" style="width:50%;height:auto;">
    
We see that $h=-0.598$ for carbon. At $120^o$ the denominator of $g(\theta)$ goes like this 
    
\begin{equation}
g(120^o)=1+\frac{c^2}{d^2}-\frac{c^2}{[d^2+(-0.598-cos120^o)^2]} \\
g(120^o)=1+\frac{c^2}{d^2}-\frac{c^2}{[d^2+(-0.598-(-0.5))^2]} \\
g(120^o)\approx 1+\frac{c^2}{d^2}-\frac{c^2}{d^2} \\
g(120^o)\approx 1
\end{equation}
    
This minimises $\zeta_{ij}$ and therefore maximises the $b_{ij}$ which corresponds to the bond strength (attractive force) making the bond strength maximal.
    
(vv proud of this deduction, I actually made it up myself and it works  meaning I think I understand this topic) :~)
    
###  End of example
    
In the end, this is what the potential looks like. We can see that for a larger bond order term $b_{ij}$ the lower (negative) the potential meaning it is more attractive at a certain distance away from the particle. 
    
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Bond-order_interatomic_potential.png/350px-Bond-order_interatomic_potential.png" alt="https://commons.wikimedia.org/wiki/File:Bond-order_interatomic_potential.png"> 

This type of potential would be ideal for comparison with DFT simulations and neural-net potenials as it is more comprehensive than a normal classical potential however still misses the mark when it comes to simulating a variety of environments as its purpose is rather specific and not general.
    
J. Tersoff, Phys Rev B, 37, 6991 (1988).

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 7 (02/11/20 - 08/11/20)<ins></h2><br>

## 7.1 Voluntary presentation for Steve Hepplestone
    
Created presentation for steve hepplestone outlining the project and 

1
<img src="https://i.imgur.com/KD5O6Dn.png" alt="" style="width:500px;height:auto;">
2
<img src="https://i.imgur.com/3BhihS9.png" alt="" style="width:500px;height:auto;">
3
<img src="https://i.imgur.com/XH9HCs8.png" alt="" style="width:500px;height:auto;">
4
<img src="https://i.imgur.com/RqwDkHH.png" alt="" style="width:500px;height:auto;">
5
<img src="https://i.imgur.com/pShFAKb.png" alt="" style="width:500px;height:auto;">
6
<img src="https://i.imgur.com/Zz9W0vM.png" alt="" style="width:500px;height:auto;">
7
<img src="https://i.imgur.com/l1R6QOh.png" alt="" style="width:500px;height:auto;">
8
<img src="https://i.imgur.com/LIoj39n.png" alt="" style="width:500px;height:auto;">
9

During our meeting, Dr. Hepplestone's Phd student was present and outlined his project  it is similar to mine however goes around it backwards. It uses machine learning to genereate the DFT data instead of learning from it. The system they are studying contains carbon with sp-2 and sp-3 bonds. The system however is very small, Dr Hepplestone mentioned that we could possibly collaborate on this. The process as outlined in the meeting was:
    
## Progression
    
<ol style="font-weight:normal; font-size:1.5rem">                                          
  <li> Take small carbon structure VASP simulation data from Joe </li>
  <br>
  <li> Create a nn potential for sp2 & sp3 seperately </li>
  <br>
  <li> Generate larger structure simulation </li>
  <br>
  <li> Send simulation outcome to Joe </li>
  <br>
  <li> Joe says if the simulations are accurate against DFT, if they are they ca
n use them to generate more DFT simulations</li>            
</ol> 
<br>
    
Steve Hepplstone mentioned that Ideally getting some good results by the beginning of January would be ideal for them to try use my data generated.
    
## 7.2 sp-2 \& sp-3 Hybridisation Carbon Bonds
    
However, this is betting on the fact that the data will be enough to give a good potential (which I doubt, but worth a try I literally have nothing to lose). If not I will try to work with Joe to create a simple melt quench simulation on a graphene structure and use this data to train my nn potential network. This would first require also simulating graphene using the Tersoff potential described yesterday.
    
Either way, I have mostly decided that I will be using carbon for my final strucure, whether it is from data Joe generated or elsewhere. Hence, I would be good to educate myself on sp-2 and sp-3 bonds. 
    
Upon Joe's reccomendation, I decided to do some reading in this sphere and found a few sources. One of my colleagues from Physics is currently studying graphene so we had a discussion about how these bonds work on the wavefunction level. I will use this space as a summary of my understanding for future reference.
    
The concept of hybrydisation arised from the failure of valence bond theory to explain bonding of Carbon and Hydrogen. The Carbon ground state is.

<img src="https://imgur.com/SUdyj86l.png" style="width:50%;height:auto;">

According to valence bond theory, we should get 2 Hydrogen bonds as there are two unpaired electrons in the 2p orbitals resulting in CH$_2$. Experiments showed that CH$_2$ is extremely reactive and not stable. Therefore, we see that this theory does not support the existance of stable CH$_4$. 
    
For this to be possible, we need 4 unpaired electrons. This happens where the 2s orbital and 3 2p orbitals fuse together to create a hybrid orbital. Then the electron configuration looks like this.
    
<img src="https://imgur.com/7IMbUf5l.png" style="width:50%;height:auto;">
    
This is actually energetically favourable as the energies are smaller than the unhybridised mode.
    
What is basically happening here is the superposition of the 2s and 3 2p wavefunctions $|s>$,  $|p_x>$, $|p_y>$ and $|p_z>$. This then leads to different posibilities of the arrangement of atoms. sp, sp2 and sp3.
    
To carbon bonds, sp2 and sp3 are the most important. 

### 7.2.1 sp2 Bonds (Graphene \& Graphite)
    
In sp2 hybridisatio, the 2s orbital and two of the 2p orbitals superpose or "hybridise" to form three sp orbitals.
    
<img src="https://imgur.com/DkpNDEKl.png" style="width:80%;height:auto;">

This superposition leads to a "triangular" planar structure. This means that there are 3 sp orbitals in a plane each orientated at an angle of 120$^o$ and one p orbital perpendicular to the plane.

The final orbital for C-C in bonding looks like this.
   
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fasdn.net%2Fasdn%2Fchemistry%2Fimages%2Fsp2.jpg&f=1&nofb=1" style="width:50%;height:auto;">
    
This planar structure of bonds then leads to the hexagonal shape of graphene with angles of 120$^o$. 
    
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.researchgate.net%2Fprofile%2FRadek_Zboril%2Fpublication%2F324009524%2Ffigure%2Fdownload%2Ffig2%2FAS%3A631608981876763%401527598724260%2Fa-Pictorial-representation-of-graphene-sheet-and-b-sp-2-hybridization-in-graphene.png&f=1&nofb=1" style="width:50%;height:auto;">

The sp-2 bonds are what we are looking at as we are looking at graphene however the p orbitals are responsible for graphite structure linking planes together "vertically".

    
### 7.2.2 sp3 Bonds (Diamond)
    
The hybridisation of the 2s orbital with all 3 of the 2p orbitals ($p_x,p_y,p_z$). This creates 4 sp orbitals at angles of 109.5$^o$ to eachother.
    
<img src="https://imgur.com/kBEGw23l.png" style="width:80%;height:auto;">

This ends up giving rise to a tetrahedral structure seen in diamond (carbon) or Silicon Dioxide. In this example the $|s>$ wavefunction superposes with all of the three p orbital wavefunctions $p_x,p_y,p_z$ giving 4 sp orbitals and therefore 4 bonds in 3D space (not 2D like Graphene).
    
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimage.slidesharecdn.com%2F2012-topic14-1hybridizationandbondinghl-120124084224-phpapp02%2F95%2F2012-orbital-hybrization-sigma-and-pi-bonds-12-728.jpg%3Fcb%3D1327395017&f=1&nofb=1" style="width:50%;height:auto;">

Another sucessful analysis. Well done me. Honestly its difficult keeping up with this without much guidance. Imposter Syndrome is r e a l.

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 8 (09/11/20 - 01/11/20)<ins></h2><br>

## 8.1 Joe's DFT data
    
>Hi Natan,
>
>Sorry it took me a while to get back to you. I have attached some data that might be useful.
>
>Here is the random structure search result, and I'll attach the POSCARs for the results above
> <img src="https://imgur.com/J7uzHUn.png" style="width:70%;height:auto;">
>Hopefully this is useful to you ,                   
>                                                    
>Cheers,                                             
>                                                    
>Joe Pitfield 
    
This week I got an email from Joe with the wrong kind of data so I cannot move on with the project. I was sent POSCAR data which only describes the initial position of the system and the lattice parameters. I emailed him to get the OUTCAR data I used for the SiO2 simulation to show what type of data I need. 
    
He isn't responding.

## 8.2 DFT Summary Explanation

Since Joe Pitfield is not replying and I cannot move in with the project I would like to use this time to explain more about the theory behind DFT calculations for future reference. This will not be an exhaustive overview of DFT as it isnt the main focus of my project.
    
This was compiled using mostly a paper suggested by Joe and a talk "Fundamentals and applications of density functional theory - Astrid Marthinsen (Norwegian University) https://www.youtube.com/watch?v=SXvhDLCycxc". 
    
DFT in summary is the process of finding the lowest energy of a system from first principles calculations. The purpose of it is to replace the extremely demanding process of solving the Schrodinger equation for many body systems due to the great complexity. Schrodinger equation solutions are only accurate for Hydrogen atom as it is a 2 body system. For anything past 3 bodies, approximate methods are used.
    
DFT goes around this problem with a number of approximations. First one being the Born-Oppenheimer Approximation. This essentially means $m_{nuclei} >> m_{e}$. This essentially decouples the dynamics of the nucleus to the dynamics of the electrons. This means we can treat them seperately so the wavefunction looks like.
    
\begin{equation}
    \Psi({r_i}{R_i}) \rightarrow \Psi_N({R_i}) \ast \Psi_e({r_i})
\end{equation}
    
This is still extremely difficult to compute as it scales as 3N where N is the number of atoms. To solve this, we can utilise the Hohenberg-Kohn theorems.
    
### Hohenberg-Kohn Theorems
    
<ol>
    <li>Ground State Energy is a unique functional of the electron density.</li>
    <li>Electron density that minimises the energy functional gives the true ground state energy.</li>
</ol>
    
This means that we can use the electron density to get to the final lowest energy state.
    
\begin{equation}
    n(r) = \Psi\text{*}({r_i})  \Psi({r_i})
\end{equation}
    
This then takes the problem from 3N to 3 dimensions as only n(r) needs to be found. This is because the groundstate energy only depends on the electron density.
    
Through a minimisation algorithm we can obtain the grounds state of a system.
<br>
<img src="https://i.imgur.com/Cmf5sJd.png">
<br>

(This flowchart is original content based on the method described in the talk given by Astrid Marthinsen.)
    
This is the method DFT uses to "relax" the system and get the ground state. Once again, this is not a comprehensive description of DFT as it is beyond the scope of this project however this concept will be needed later on when parsing the positional data from the VASP calculations.
    
I still havent gotten data from Joe so I am going to stop for this week.

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 9 (16/11/20 - 22/11/20)<ins></h2><br>

Finally I recieved the correct type of data. The data is obviously not obtained for my purposes exactly which means that the network may not train accurately on it.
 
The specifications of the VASP output data that SIMPLE-NN needs as specified in the documentation is that the file has to contain:
    
> atom coordinates, lattice parameters, energy, and forces
    
As SIMPLE-NN uses python's "ase" Atomic Simulation Environment library for the VASP output files, we can do the same manually to extrac the relevant data. 
    
some of the ase's methods that will be useful for checking this are:
    
- io.read('vasp_output') -> returns "Atoms" object which then we can use the following methods on.

- get_positions() 

- get_chemical_symbols()

- get_cell()

- get_potential_energy()

- atoms.get_forces()

- atoms.get_stress()
    
As long as all of these methods on the vasp Atoms object give outputs, SIMPLE-NN should be able to handle and read in the OUTCAR data.
    
I wrote a script that checks all of these values for a given OUTCAR file.
    
<pre><code>
#!/usr/bin/python3    
    
from ase import io    
    
output = "OUTCAR_"    
    
atoms = io.read(output)    
print("File: " + output + "\n")    
print("Positions:\n")    
print(atoms.get_positions())    
print("\n")    
print("Chemical Symbols:\n")    
print(atoms.get_chemical_symbols())    
print("\n")    
print("Cell:\n")    
print(atoms.get_cell())    
print("\n")    
print("Potential Energy:\n")    
print(atoms.get_potential_energy())    
print("\n")    
print("Forces:\n")    
print(atoms.get_forces())    
print("\n")    
print("Stress:\n")    
print(atoms.get_stress())    
print("\n")
</code></pre>
    
I can now test all of these values given an OUTCAR file. Firstly, I tried it for the SiO2 OUTCAR vasp output that was used in the first SIMPLE-NN run. This is a good benchmark as the creators of SIMPLE-NN managed to derive a accurate potential out of this data.
    
<pre><code>
    
File: OUTCAR_comp

Positions:

[[ 2.322710e+00  0.000000e+00  3.600000e+00]
 [ 4.644960e+00  5.000390e+00  3.021790e+00]
 [ 4.972350e+00  8.354960e+00  6.906780e+00]
 [-3.786600e-01  1.602650e+00  2.850100e+00]
 [ 2.703940e+00  2.596690e+00  9.514190e+00]
 [-3.369420e+00  8.166110e+00  9.516570e+00]
 [ 7.453040e+00  2.740900e-01  4.806550e+00]
 [ 3.057170e+00  4.006890e+00  5.330650e+00]
 [ 1.157500e+00  2.538480e+00  6.909310e+00]
 [-8.410000e-01  8.380900e+00  1.115350e+00]
 [-2.072000e-02  6.774750e+00  9.426560e+00]
 [ 2.294730e+00  5.184240e+00  2.001000e-01]
 [ 1.311860e+00  6.750290e+00  2.655390e+00]
 [ 2.189270e+00  8.343270e+00  8.756180e+00]
 [ 7.968840e+00  1.343960e+00  3.108300e-01]
 [-9.795500e-01  4.678830e+00  2.737950e+00]
 [ 8.216950e+00  2.694190e+00  8.435760e+00]
 [ 4.869130e+00  1.536610e+00  4.710850e+00]
 [ 4.793730e+00  4.463260e+00  9.769120e+00]
 [ 6.372890e+00  5.925610e+00  9.326300e-01]
 [-2.893570e+00  5.648870e+00  4.813850e+00]
 [ 4.043220e+00  5.917560e+00  7.453100e+00]
 [-2.209080e+00  5.665170e+00  7.946980e+00]
 [ 5.308280e+00  2.278720e+00  1.776200e+00]
 [ 3.642580e+00  6.024300e-01  4.336990e+00]
 [-1.278270e+00  2.364600e+00  9.999370e+00]
 [-2.353000e+00  5.575230e+00  6.338520e+00]
 [ 2.234800e-01  4.060000e-03  8.611080e+00]
 [ 2.418670e+00  9.839400e-01  9.830870e+00]
 [ 1.135400e+00  6.032760e+00  1.023429e+01]
 [ 4.372810e+00  2.935710e+00  9.601880e+00]
 [ 1.021890e+00  9.401200e-01  3.402740e+00]
 [-3.756500e-01  2.923830e+00  7.330570e+00]
 [-2.001310e+00  5.364320e+00  1.472900e+00]
 [ 3.275320e+00  4.816630e+00  3.885050e+00]
 [ 2.187840e+00  3.051070e+00  8.100000e+00]
 [ 5.209260e+00  6.234850e+00  2.178960e+00]
 [ 7.510000e-03  5.978200e+00  3.136550e+00]
 [ 4.267770e+00  2.885700e+00  5.501790e+00]
 [ 6.777090e+00  2.128280e+00  1.050820e+00]
 [-2.872220e+00  7.175860e+00  4.417060e+00]
 [-9.404500e-01  7.519510e+00  1.057203e+01]
 [-2.141120e+00  8.039130e+00  2.023910e+00]
 [ 7.282740e+00  1.289370e+00  7.949600e+00]
 [-3.629560e+00  7.276510e+00  1.507000e-02]
 [ 5.631580e+00  4.879160e+00  4.352760e+00]
 [ 3.059740e+00  5.072860e+00  6.479070e+00]
 [ 2.972010e+00  6.974010e+00  8.179340e+00]
 [-2.817020e+00  7.055260e+00  8.426060e+00]
 [ 4.660600e+00  3.877140e+00  1.808810e+00]
 [-6.138700e-01  5.749530e+00  8.314210e+00]
 [ 6.082670e+00  4.697240e+00  1.067182e+01]
 [ 9.056170e+00  8.558200e-01  1.436790e+00]
 [ 5.535000e-01  7.977170e+00  1.872400e+00]
 [-1.744150e+00  4.744700e+00  4.106770e+00]
 [ 5.177180e+00  6.786190e+00  6.518730e+00]
 [-2.302200e-01  3.268250e+00  2.412930e+00]
 [ 8.203790e+00  1.355930e+00  3.930560e+00]
 [ 2.176390e+00  7.550240e+00  3.828500e+00]
 [ 2.151580e+00  5.836020e+00  1.672490e+00]
 [ 1.119780e+00  9.506200e-01  6.479190e+00]
 [ 8.504640e+00  2.360000e-02  6.067980e+00]
 [ 3.692330e+00  5.525710e+00  1.035954e+01]
 [ 7.338010e+00  4.060240e+00  8.489880e+00]
 [ 5.678350e+00  1.939290e+00  3.333810e+00]
 [ 2.696570e+00  8.487450e+00  1.037074e+01]
 [ 6.052060e+00  6.815900e-01  5.460830e+00]
 [ 1.984410e+00  3.495790e+00  1.076447e+01]
 [ 5.058970e+00  5.074630e+00  8.324130e+00]
 [ 5.870500e-01  8.055760e+00  8.518340e+00]
 [ 1.612560e+00  3.310340e+00  5.546260e+00]
 [ 4.147840e+00  1.420290e+00  9.662400e-01]]


Chemical Symbols:

['Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'Si', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']


Cell:

Cell([[9.842000008, 0.0, 0.0], [-4.921000004, 8.523422031, 0.0], [0.0, 0.0, 10.800000191]])


Potential Energy:

-555.01560862


Forces:

[[ 0.927569 -1.05281  -1.835859]
 [ 0.282093 -1.313129  1.369744]
 [-0.695334 -0.220082  0.656239]
 [-0.815823  0.4308   -0.209705]
 [ 0.915249 -0.892587  3.697287]
 [-0.399397 -0.964599 -1.182755]
 [ 1.092713 -1.375084  1.193119]
 [ 1.251802 -0.587846 -1.917022]
 [-1.046294  0.277104 -0.436811]
 [ 0.449126 -2.615044  1.402399]
 [ 0.637406  1.201506 -0.793141]
 [-2.762928 -1.080211 -0.278254]
 [-0.59264   2.463595  1.056572]
 [ 0.597387  0.384213 -0.402852]
 [ 0.78873   0.051511  0.336708]
 [-0.211263  2.800629 -1.254644]
 [-0.865355 -1.193787 -0.76479 ]
 [ 0.807113  1.272248  0.450201]
 [ 0.873379  0.706853  1.073203]
 [ 0.141931  0.16748   0.558501]
 [ 1.608751 -1.090345  1.457733]
 [-1.230747  2.585736 -1.964215]
 [ 0.622104 -2.642969 -1.556816]
 [ 0.412445  1.399374 -0.073915]
 [-1.42651  -0.128937 -0.295397]
 [ 0.984473  0.451264 -0.302508]
 [-0.32375  -0.324046  0.438445]
 [-1.104634  0.695861 -0.60962 ]
 [-0.298     1.03954  -0.7333  ]
 [ 0.251083 -0.893718 -0.099321]
 [-2.085906 -1.178565 -0.225219]
 [-0.501407  0.773779  0.065286]
 [-0.544922 -0.422759  1.125585]
 [ 0.615542 -0.863969  1.386116]
 [-1.431297 -0.67366   0.318846]
 [-0.971847 -0.543564 -1.796339]
 [ 1.273089  0.853765 -1.646374]
 [ 0.061432 -2.176559 -0.099836]
 [-0.006696 -1.163584 -0.361056]
 [-1.540658  0.478479  0.342511]
 [-0.543719  1.408456 -0.547856]
 [-0.171914 -0.848799 -1.381053]
 [-0.563896  0.725021  1.846967]
 [ 1.422972  1.039974  1.57053 ]
 [-0.376593 -0.062451  0.942975]
 [-0.776076 -0.122249 -0.539721]
 [ 0.997526  1.442519  1.637612]
 [ 0.49363   0.125101 -0.178184]
 [ 0.754465  0.548658  0.74972 ]
 [ 0.544823 -2.599506  0.758547]
 [-0.039154  0.468362  0.915199]
 [ 0.478316  0.433127  0.601586]
 [ 0.3645    0.687765  0.55069 ]
 [ 0.39452   0.631822 -0.679196]
 [-0.907399 -1.258298  0.582545]
 [-0.948725 -0.583327  0.82113 ]
 [-0.440751 -1.215783  0.780001]
 [ 2.515151  1.90175  -1.939781]
 [ 0.005264 -1.595438 -0.805799]
 [ 1.52644  -1.2304   -0.207377]
 [ 1.294065  0.775034 -0.454019]
 [-0.501672  0.417025 -0.770581]
 [ 0.698066 -0.415874 -0.117662]
 [ 0.213517  0.901623 -0.843597]
 [-1.270561  0.450236 -0.378867]
 [-1.337013 -0.69222  -1.899443]
 [-1.630232  1.179363  0.692914]
 [ 0.910085  1.21351  -0.613854]
 [ 0.069491 -0.137113 -0.926155]
 [ 0.440567 -0.801776  1.208123]
 [-0.525517 -0.405175 -0.366412]
 [ 1.049461  2.654323  0.6395  ]]


Stress:

[-0.0229063  -0.00791085 -0.01643499  0.01387617  0.00922461 -0.01354811]
</code></pre>
    
And here is the output of the data given by Joe.
    
<pre><code>
File: OUTCAR_001

Positions:

[[0.53427 1.24768 0.96025]
 [0.55517 1.14928 2.39033]]


Chemical Symbols:

['C', 'C']


Cell:

Cell([[2.122716366, -0.103891041, 0.15158254], [-0.190623596, 2.121638116, -0.04251178], [0.042421517, -0.194651961, 2.860302343]])


Potential Energy:

-13.56910997


Forces:

[[ 0.000249 -0.000853 -0.000103]
 [-0.000249  0.000853  0.000103]]


Stress:

[-5.18669408e-06 -1.46113729e-05 -2.31559989e-06  1.15155843e-05
  1.10911617e-05  7.91423357e-06]
</code></pre>

Here clearly lays a glaring issue. There are only two carbon atoms in the simulation. This is not much use as we are trying to study the behaviour of a system of around 72 atoms just like the one from the previous example. Technically I can still use this data as it does contain the behaviour of the correct environment and I have around 30 runs of sp2 structure minimisation. However, I will enquire to Joe to try run a simulation of an sp2 system for heating it up instead.
    
I emailed Joe Pitfield and he said that the runs are minimisation of the unit cell of the structure which is exactly what I thought. This is clearly not very useful if we are trying to train a neural network based on the number of atom positions. We talked about simulating an sp2 structure of tens of carbon atoms I can use to simulate a larger piece of graphene.

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 10 (23/11/20 - 29/11/20)<ins></h2><br>

# 10.1  Catchup
    
A lot of this week was used to catch up with some of the other weeks to get more comprehensive outline of the topic.
    
I came up with a pipeline that I will use for the project. This time I wont make a flowchart because time.
    
* DFT Simulation (Joe's Help with VASP) -> 
* Symmetry Functions (Inside SIMPLE-NN) -> 
* Neural Network (SIMPLE-NN) -> 
* Potential output file ->
* LAMMPS (pair_style,pair_coeffs) -> 
* positionstr output file -> 
* Analysis in OVITO (Visualisation, melting point, radial distribution function [phononic dispersion/DOS?])
    
This is going to be mainly the structure of my project. The final goal of the project will be to comapare the accuracy of the three different methods: DFT, Tersoff, nn for the same structure. This would be done by finding different properties for each one.
    
Another fantastic thing I found out is that the Behler-Parinello method can be carried out in a program called AMS2020. This is a GUI program which does not reveal anything about how the method actually works so I will definitely be sticking to the lovely python/C++ implementation of SIMPLE-NN and its fantastic documentation.
    
# 10.1  Revision of Behler-Parinello Method
    
As I am most likely going to be asked about this during the viva. I am going to revise the full method of Behler-Parinello as I have not read about it properly since last year considering I was learning all of the things mentioned previously.
    
This is generally the motto of this method:
  
> Regression model on the relationship between atomic configurations and total energies.
    
The reason for using this method is because it is nearly as accurate as DFT with the computational cost of Classical Simulations. Here is a qualitative graph showing this trend and where ML potentials fit in.
   
<img src="https://i.imgur.com/SCrN6iB.png" style="width:40%:height:auto;">
<small>Interatomic potentials from first principles - https://www.youtube.com/watch?v=aVY-UViqL-E</small> 

The neural net and symmetry functions have been explained in my lab book end of last year in Section 7.1.2 and 7.1.3 (Week 2).
    
Here is a snippet of the lab book.
    
<img src="https://i.imgur.com/5JKt1Gd.png" style="width:50%:height:auto;">
<img src="https://i.imgur.com/6DsrQLR.png" style="width:50%:height:auto;">
    
This is the diagram for the flow/network of the program taken from the SIMPLE-NN paper. 
    
<img src="https://i.imgur.com/Ix8W1OC.png" style="width:30%:height:auto;">
    
In part a) we see how firstly the cartesian coordinates are passed on to the symmetry functions to be used by the neural network. 
    
The main part of this entire method is making sure we get the correct symmetry functions to describe the system. In the iteration of the Behler-Parinello method I am using there are 3 symmetry functions (One radial(2 body), 2 Angular (3 body)) that are fitted to describe the environment around each atom in the simulation.
    
<img src="https://i.imgur.com/OZN6ZcN.png" style="width:30%:height:auto;">
    
Similarily to the Tersoff Potential, these are fitted with parameters to describe the system. This could be done manually however it would be counterintuitive to do it this way and it is simple enough to have code to do it for us. Fortunately SIMPLE-NN has a symmetry function fitting feature. The number of parameters to be optimised per symmetry function go like this radial G2(2 parameters) | angular G4(4 parameters) | G5(5 parameters) $\nu$ and $R_s$ are used for G2. The anuglar functions take in the previous two together with $\nu$, $\zeta$ and $\lambda$.
    
Once optimised, each type of symmetry function is saved as a vertex $G_i({R_i})$ in a python pickle file. Then the values are normalised between -1 and 1 and fed into the neural network. This gives the neural network the description of the local environment for each atom. (The symmetry functions are optimised using DFT data). There is a solution for fixing the sampling bias which is called GDF optimisation This prevents imperfections in the material in DFT calculations to transfer to the NN potential simulations. 
 
These normalised symmetry functions are then passed onto Tensorflow here test-train data is split and the neural network is trained using the Adam optimiser. There are other optimisers available however from what I have seen Adam is the standard as it is so ahead of the competition.
    
The simple-nn paper also mentiones that to speed up the computing time we can alter the loss function to only include the RMSE in Energy (exclude Force RMSE) however this apparently leads to bias with smaller datasets.
    
After the training is complete, the final form of the neural network is saved as "potential_saved_iteration" This contains the symmetry functions on top and the final state of the neural network in the end. This is then passed to LAMMPS in form of the custom "pair_style" command which is a template that takes in parameters (just as Tersoff just this time parameters are symmetry functions parameters and network weights).
    
This pair_style is a 900 line code of C++ code with little to no documentation so it is really a quest to find what works but from dissecting the code, I see that the code creates symmetry functions for each one of the particles at the time, inputs them into the neural network and obtains a Potential Energy Surface which is then used by LAMMPS to iterate a new step. The literature on this is quite limited and everything i have go off of is from the code so it may not be right. 
    
This is a diagram of the process in question.
    
<img src="https://i.imgur.com/AqeZq1c.png" style="width:40%;height:auto">
    
For this week I am done, next week I will prepare for the viva and create a presentation.

<h2 style="margin-top: 0.2em;text-align:center"> <ins>Week 11 (30/11/20 -  06/12/20) VIVA<ins></h2><br>

# 11.1 Admin Work/ Viva Prep

Most of the week was spent on admin work, clearing up concepts and organising input and outputs. I had a meeting with Saverio Russo and Max which I connected to online. During the meeting I outlined my progress so far and agreed with Prof. Russo that my viva needs to be more strucutred therefore I will create a small presentation to show during the viva. I will also have the relevant systems up for the viva for when they are needed to explain a concept.

For the rest of the week im going to be working on the presentation but when i get bored im gonna try get graphene to work with a tersoff potential. 

# 11.2 Graphene Tersoff Potential

Also managed to get Tersoff Potential to work for a set of graphene at 300K. This code I mainly wrote however I did copy and paste some things in order to get the LAMMPS manybody potential to work. I also had to rebuild LAMMPS with the MANYBODY extension to get access to the form of the Tersoff form. This is essentially just a C++ script which intakes the parameters needed for three particles and outputs.

<pre><code>

# Title: Graphene LAMMPS input script
# By: Natan Szczepaniak

# First input script which uses SIMPLE-NN generated potential
# to simulate Graphene.


# 1) Setting up the simulation box

units	 metal
atom_style atomic
dimension 2
boundary p p p
processors * * *
newton on

  
lattice custom 1.0 a1 2.13 1.2297 0.0  a2 0.0 2.4595 0.0 a3 0.0 0.0 6.7  &
                 basis 0.0 0.0 0.0  basis 0.5773 0.0 0.0

region mySheet block  0 10 0 10 0 1 units lattice

# Create sheet of carbon atoms
create_box 1 mySheet
create_atoms 1 region mySheet
mass * 12.0107

# Set initial temperature
velocity all create 300.0 5432373 dist gaussian

# 2) Define interparticle ineractions (Tersoff potential)

pair_style tersoff
pair_coeff * * SiC.tersoff C


# 3) List of Neighbours (Neighbor lists are recalculated 
# each timestep.)

neighbor 2.0 bin
neigh_modify delay 3

# 4) Command Line output setup  (Thermo)

timestep        0.00001

thermo_style    custom step temp etotal pe ke press vol density
thermo          10              

run_style verlet

run 10000



# 5) Output file form for ovito
dump            2 all custom 10 positionsgraphene.lammpstrj id type x y z vx vy vz
dump_modify     2 sort id

# 6) Minimisation of system energy

# Conjugate Gradient minimisation of energy
min_style cg
minimize 1e-6 1e-6 10000 10000


# For future dynamics simulations after it has been relaxed
#
#fix dynamics all nve
#
#fix heating all temp/berendsen 300.0 1000.0 0.0001
#
#run 1000
#
#unfix heating
#
##fix cooling all temp/berendsen 1000.0 1.0 0.0001
#
##run 100000
#
##unfix cooling
#
##-----------
#unfix dynamics
#undump graph

</code></pre>
    
The coefficients for the Tersoff Potential are obtained from the SiC.tersoff file that comes with the MANYBODY package for LAMMPS. This is a snippet of what is relevant. It gives the parameters for a three body inteaction and the form that they are given in.
    
<pre><code>
# Si and C mixture, parameterized for Tersoff potential
# this file is from Rutuparna.Narulkar @ okstate.edu
# values are from Phys Rev B, 39, 5566-5568 (1989)

# Tersoff parameters for various elements and mixtures
# multiple entries can be added to this file, LAMMPS reads the ones it needs
# these entries are in LAMMPS "metal" units:
#   A,B = eV; lambda1,lambda2,lambda3 = 1/Angstroms; R,D = Angstroms
#   other quantities are unitless

# format of a single entry (one or more lines):
#   element 1, element 2, element 3,
#               m, gamma, lambda3, c, d, costheta0, n,
#               beta, lambda2, B, R, D, lambda1, A

C   C    C   3.0 1.0 0.0 38049  4.3484   -.57058 .72751
             0.00000015724 2.2119  346.7   1.95   0.15   3.4879  1393.6
</code></pre>

The conjugate Gradient minimisation algorithm preprogrammed into lammps minimises the energy of the system. After the system stabilises, it will still have some oscillation around its point as the temperature is 300K but not much.

This is the final snapshot of the system.
 
<img src="https://i.imgur.com/Jb0QWTy.png" style="width:50%;height:auto;">

And here is the RDF over time after the structure has stabilised. There is a little bit of vibration as once again, the temperature is non-zero.

<img src="https://i.imgur.com/I3iSQ63.gif">
    
To be fair this is more than I wanted to do for the week so i'm going to give myself a pat on the back and carry on with making the presentation.